name: travel_ease
description: "A Travel Destination App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  go_router:  ^15.1.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2

  permission_handler: ^12.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  numberpicker: ^2.1.2

  flutter_staggered_animations: ^1.1.1
  flutter_stripe: ^11.5.0
  dio: ^5.8.0+1

  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.13.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_generator: ^2.0.1


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets
    - assets/images/
    - assets/images/profile.webp
    - assets/images/city/
    - assets/images/country/
    - assets/images/iceland/
    - assets/images/lake/
    - assets/images/mountain/
    - assets/images/logos/







  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Reg^12.0.0+1f
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
