// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD781TSqyP89HDjiFd89YrurUpUnhtMHO8',
    appId: '1:477776670675:web:9a6539df6ca72d210cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    authDomain: 'authentication-5671f.firebaseapp.com',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    measurementId: 'G-X81ZB6VC38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vWSHW-nLUn7IgfODgRARIRn9geRaPm8',
    appId: '1:477776670675:android:3d1fc53674a9951d0cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    storageBucket: 'authentication-5671f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tptd8wiIupetJfvZkYCm0IWh8lCkAZc',
    appId: '1:477776670675:ios:ebde59b7ffe271a40cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    androidClientId: '477776670675-u9usjldriiv6mpsbeml3ub5195g8ic1v.apps.googleusercontent.com',
    iosClientId: '477776670675-9vcef70q8pog977qaqqvm08g3m4drneb.apps.googleusercontent.com',
    iosBundleId: 'com.example.heroAnim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD781TSqyP89HDjiFd89YrurUpUnhtMHO8',
    appId: '1:477776670675:web:39393748b5a851c40cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    authDomain: 'authentication-5671f.firebaseapp.com',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    measurementId: 'G-HS73C94EKC',
  );
}
