// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD781TSqyP89HDjiFd89YrurUpUnhtMHO8',
    appId: '1:477776670675:web:93f89a6c941a5c4b0cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    authDomain: 'authentication-5671f.firebaseapp.com',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    measurementId: 'G-S4RKB75R1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vWSHW-nLUn7IgfODgRARIRn9geRaPm8',
    appId: '1:477776670675:android:86a958274962318b0cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    storageBucket: 'authentication-5671f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tptd8wiIupetJfvZkYCm0IWh8lCkAZc',
    appId: '1:477776670675:ios:d9b7ec2a17e29fe70cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    iosClientId: '477776670675-9vcef70q8pog977qaqqvm08g3m4drneb.apps.googleusercontent.com',
    iosBundleId: 'com.example.heroAnim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tptd8wiIupetJfvZkYCm0IWh8lCkAZc',
    appId: '1:477776670675:ios:d9b7ec2a17e29fe70cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    iosClientId: '477776670675-9vcef70q8pog977qaqqvm08g3m4drneb.apps.googleusercontent.com',
    iosBundleId: 'com.example.heroAnim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD781TSqyP89HDjiFd89YrurUpUnhtMHO8',
    appId: '1:477776670675:web:c2c89113847e63240cc926',
    messagingSenderId: '477776670675',
    projectId: 'authentication-5671f',
    authDomain: 'authentication-5671f.firebaseapp.com',
    storageBucket: 'authentication-5671f.firebasestorage.app',
    measurementId: 'G-E16WPW06GJ',
  );
}
